//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantSurveyApp.Mvc.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public Applicant()
        {
            this.Surveys = new HashSet<Survey>();
        }
    
        public int ApplicantID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<Survey> Surveys { get; set; }
    }
}
