//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantSurveyApp.Mvc.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageDetail
    {
        public int ImageID { get; set; }
        public string Location { get; set; }
        public string Comment { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public bool Active { get; set; }
    }
}
