//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantSurveyApp.Mvc.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQuestion
    {
        public int QuestionID { get; set; }
        public string QuestionDescription { get; set; }
        public int QuestionTypeID { get; set; }
    }
}
